services:
  - type: web
    name: diabetes-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10001
    envVars:
      - key: PORT
        value: 10000
